# Generated by Django 2.2.6 on 2019-10-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=22)),
                ("email", models.EmailField(max_length=90)),
                ("cep", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=100)),
                ("iptu", models.CharField(max_length=100)),
            ],
        )
    ]
