version: "3.7"

services:
  app:
    image: gcr.io/spot-that-fire-256218/app
    volumes:
      - data:/root/data
    networks:
      - proxy
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        traefik.enable: "true"
        traefik.django.port: "8000"
        traefik.docker.network: "proxy"
        traefik.django.frontend.rule: "Host:www.${DOMAIN?Variable DOMAIN not set},${DOMAIN}"
        traefik.django.frontend.entryPoints: "http,https"
        traefik.django.frontend.redirect.entryPoint: "https"
        traefik.flask.port: "4000"
        traefik.flask.frontend.rule: "Host:www.${DOMAIN?Variable DOMAIN not set};PathPrefixStrip:/sms"
        traefik.flask.frontend.entryPoints: "http,https"
        traefik.flask.frontend.redirect.entryPoint: "https"

volumes:
  data:

networks:
  proxy:
    external: true
