version: "3.7"

services:
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      CONSUL_BIND_INTERFACE: "eth0"
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    networks:
      - default
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"
        traefik.port: "8500"
        traefik.frontend.rule: "Host:consul.${DOMAIN?Variable DOMAIN not set}"
        traefik.frontend.entryPoints: "http,https"
        traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.auth.basic.users: "${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}"
  
  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      CONSUL_BIND_INTERFACE:  "eth0"
      CONSUL_LOCAL_CONFIG:    '{"leave_on_terminate": true}'
    networks:
      - default
      - proxy
    deploy:
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
  
  traefik:
    image: traefik:1.7
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --acme
      --acme.email=${EMAIL?Variable EMAIL not set}
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true     --consul.endpoint="consul-leader:8500"
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - default
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"
        traefik.port: "8080"
        traefik.frontend.rule: "Host:traefik.${DOMAIN?Variable DOMAIN not set}"
        traefik.frontend.entryPoints: "http,https"
        traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.auth.basic.users: "${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}"

volumes:
  consul-data-leader:
  consul-data-replica: 

networks:
  proxy:
    external: true

